In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### 1D array

In [3]:
a=np.array([10,20,30,50,60,0])

### Attributes of arrays

#### dtype

In [4]:
a.dtype

dtype('int32')

#### ndim

In [5]:
a.ndim

1

#### size

In [7]:
a.size

6

#### shape

In [8]:
a.shape

(6,)

In [9]:
a[0]

10

In [10]:
a[2]

30

### Multi dimensional array

In [11]:
a_2d=np.array([[10,20,30],[23,55,15]])

In [12]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [13]:
a_2d.dtype

dtype('int32')

In [14]:
a_2d.shape

(2, 3)

In [15]:
a_2d.ndim

2

In [17]:
a_2d.size

6

In [18]:
a_2d[0]

array([10, 20, 30])

#### first element in first array

In [26]:
a_2d[0][0]

10

#### second element in second array

In [27]:
a_2d[1][1]

55

#### change its data type into float

In [28]:
a_2d=np.array([[10,20,30],[23,55,15]],dtype=float)

In [29]:
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

#### Another type of multi dimensional array

In [21]:
at_array=np.array([[[1,2,3,4]]])

In [22]:
at_array

array([[[1, 2, 3, 4]]])

In [23]:
at_array.ndim

3

In [24]:
at_array.shape

(1, 1, 4)

In [25]:
at_array.size

4

In [30]:
arr_array=np.array([[[[1,2,3,4,5,6]]]])

In [31]:
arr_array

array([[[[1, 2, 3, 4, 5, 6]]]])

#### to get the 3rd number

In [33]:
arr_array[0,0,0,2]

3

In [37]:
arr_array[0,0,0][2]

3

#### Create a bigger array

In [3]:
a_big=np.array([[
    [10,20,30,40],[8,8,2,1],[1,1,1,2]],
    [[9,9,2,39],[1,2,3,3],[0,0,3,2]],
    [[12,33,22,1],[22,1,22,2],[0,2,3,1]]],
    dtype=float)
    

In [9]:
a_big

array([[[10., 20., 30., 40.],
        [ 8.,  8.,  2.,  1.],
        [ 1.,  1.,  1.,  2.]],

       [[ 9.,  9.,  2., 39.],
        [ 1.,  2.,  3.,  3.],
        [ 0.,  0.,  3.,  2.]],

       [[12., 33., 22.,  1.],
        [22.,  1., 22.,  2.],
        [ 0.,  2.,  3.,  1.]]])

In [4]:
a_big.shape

(3, 3, 4)

In [5]:
a_big.ndim

3

In [6]:
a_big.size

36

In [7]:
a_big[2][2][3]

1.0

In [8]:
a_big[2][2]

array([0., 2., 3., 1.])

### Filling arrays

#### np.full

In [10]:
a_full=np.full((3,5,4),7)

In [11]:
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [12]:
a_full.ndim

3

In [13]:
a_zeros=np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a_zeros.ndim

2

In [14]:
b_ones=np.ones((2,3,4))
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
b_ones.ndim

3

### Empty And Random

In [17]:
e=np.empty((4,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [21]:
e.ndim

2

In [22]:
e.size

16

In [23]:
e.shape

(4, 4)

In [18]:
b_random=np.random.random((2,2))
b_random

array([[0.71397708, 0.18174361],
       [0.89619808, 0.27042573]])

In [19]:
b_random.ndim

2

In [20]:
b_random.size

4

### Ranges

In [24]:
a_arange=np.arange(10,50,5)

In [25]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])